### ISSUE TITLE
how to get amount of data which was uploaded and downloaded? 

### ISSUE THREAD

**Issue by bizibizi** [pia-foss/client-library-apple#12]
# Summary

### Steps to reproduce
(Please provide detail steps).   

### What is the current bug behaviour?
(What actually happens).

### What is the expected correct behaviour?
(What you should see instead).

### Assignees and labels
( please add labels as applicable )    

- [ ] Patched
- [ ] Verified patch

**Comment by ueshiba** [comment]
https://github.com/pia-foss/vpn-ios/issues/1
