### ISSUE TITLE
Podfile - Error installing PIAKPIModule

### ISSUE THREAD

**Issue by Letal1s** [pia-foss/client-library-apple#13]
As of recently it seems gitlab.kape.com is inaccessible, at least to the public, making using this library troublesome. Most of the other podfile dependencies have versions hosted on GitHub, however I cannot find one for the PIAKPIModule dependency.

When running pod install, I get the following message:
```
[!] Error installing PIAKPIModule
[!] Failed to download 'PIAKPIModule': [!] /usr/local/bin/git clone git@gitlab.kape.com:pia-mobile/shared/kpi.git /var/folders/yp/fx92vncj71n_m3mlf0qgx5kw0000gn/T/d20220426-49342-e7pqap --template=

Cloning into '/var/folders/yp/fx92vncj71n_m3mlf0qgx5kw0000gn/T/d20220426-49342-e7pqap'...
ssh: connect to host gitlab.kape.com port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

How can I resolve this dependency? Thanks.

**Comment by xv-laura-s** [comment]
Hi @Letal1s. Sorry for the very late response. This issue has been fixed in our latest version. We have moved away from `Cocoapods` and we are managing dependencies with `SPM`.  
All the dependencies for this library have also been moved to public repos.
